export const ErrorCodes = {
  'CRM-901': 'Lo sentimos, no se encuentra disponible el servicio para validar la cuenta de red.',
  'CRM-902': 'Lo sentimos, no se encuentra disponible el servicio para cargar los tipos de documentos.',
  'CRM-903': 'Lo sentimos, no se encuentra disponible el servicio para validar su identidad.',
  'CRM-904': 'Lo sentimos, no se encuentra disponible el servicio para obtener su mejor huella.',
  'CRM-905': 'Se produjo un inconveniente accediendo al servicio BioMatchClient.',
  'CRM-906': 'La lectura de la huella no fue correcta.',
  'CRM-907': 'Lo sentimos, ha superado el máximo número de intentos al escanear su huella.',
  'CRM-908': 'Lo sentimos, no se encuentra disponible el servicio para validar su huella.',
  'CRM-909': 'Lo sentimos, no se encuentra disponible el servicio para enviar PIN.',
  'CRM-910': 'Lo sentimos, ha superado el máximo número de intentos de envío de PIN.',
  'CRM-911': 'Lo sentimos, no se encuentra disponible el servicio para validar el PIN.',
  'CRM-912': 'El vendedor no tiene permiso de ingresar al dashboard.',
  'CRM-913': 'Ha superado el máximo número de intentos al validar el PIN. Reenvíe un nuevo PIN.',
  'CRM-914': 'El vendedor no tiene las configuraciones adecuadas para ingresar.',

  'CRM-920': 'Lo sentimos, no se encuentra disponible el servicio para cargar los pagos pendientes.',
  'CRM-921': 'Lo sentimos, no se encuentra disponible el servicio para anular un pago.',
  'CRM-922': 'Lo sentimos, no se encuentra disponible el servicio para obtener el detalle del pedido.',

  'CRM-930': 'Lo sentimos, no se encuentra disponible el servicio para cargar las nacionalidades.',
  'CRM-931': 'Lo sentimos, no se encuentra disponible el servicio para cargar los estados civiles.',
  'CRM-932': 'Lo sentimos, no se encuentra disponible el servicio para cargar los sexos.',
  'CRM-933': 'Lo sentimos, no se encuentra disponible el servicio para cargar los departamentos.',
  'CRM-934': 'Lo sentimos, no se encuentra disponible el servicio para cargar las provincias.',
  'CRM-935': 'Lo sentimos, no se encuentra disponible el servicio para cargar las distritos.',
  'CRM-936': 'Lo sentimos, no se encuentra disponible el servicio para crear nuevo cliente.',
  'CRM-937': 'El cliente ya existe.',

  'CRM-940': 'Lo sentimos, no se encuentra disponible el servicio para cargar los tipos de operaciones.',
  'CRM-941': 'El Cliente ha excedido las 10 líneas permitidas, si desea contratar más líneas deberá acercarse a un Centro de Atención',
  'CRM-942': 'Lo sentimos, no se encuentra disponible el servicio para validar la cantidad de lineas permitidas.',
  'CRM-943': 'Lo sentimos, no se encuentra disponible el servicio para cargar la configuración biométrica.',

  'CRM-950': 'Lo sentimos, no se encuentran disponible el servicio para cargar los servicios.',
  'CRM-951': 'Lo sentimos, no se encuentran disponible el servicio para cargar los operadores.',
  'CRM-952': 'Lo sentimos, no se encuentran disponible el servicio para cargar las modalidades.',
  'CRM-953': 'El número ingresado ya existe.',
  'CRM-954': 'Lo sentimos, no se encuentra disponible el servicio para validar la portabilidad.',
  'CRM-955': 'Lo sentimos, no se encuentra disponible el servicio de consulta previa.',
  'CRM-956': 'Lo sentimos, no se encuentra disponible el servicio para generar la SEC.',
  'CRM-957': 'El tiempo para validar el PIN ha expirado.',
  'CRM-958': 'Lo sentimos, no se pudo verificar la consulta previa.',

  'CRM-960': 'Lo sentimos, no se encuentra disponible el servicio para consultar los datos de oficina.',
  'CRM-961': 'Lo sentimos, no se encuentra disponible el servicio para cargar las modalidades.',
  'CRM-962': 'Lo sentimos, no se encuentra disponible el servicio para cargar las opciones.',
  'CRM-963': 'Lo sentimos, no se encuentra disponible el servicio para validar la disponibilidad.',
  'CRM-964': 'Lo sentimos, no se encuentra disponible el servicio para cargar las campañas.',
  'CRM-965': 'Lo sentimos, no se encuentra disponible el servicio para cargar la lista de precios.',
  'CRM-966': 'Lo sentimos, no se encuentra disponible el servicio para cargar los planes.',
  'CRM-967': 'Lo sentimos, no se encuentra disponible el servicio para cargar las provincias y distritos.',
  'CRM-968': 'Lo sentimos, no se encuentra disponible el servicio para cargar los centros poblados.',
  'CRM-969': 'Lo sentimos, no se encuentra disponible el servicio para cargar los tipos de productos.',
  'CRM-970': 'Lo sentimos, no se encuentra disponible el servicio para cargar las promociones.',
  'CRM-971': 'Lo sentimos, no se encuentra disponible el servicio para añadir la linea.',
  'CRM-972': 'Lo sentimos, no se encuentra disponible el servicio para grabar la venta.',
  'CRM-973': 'Lo sentimos, no se encuentra disponible el servicio para generar los documentos.',
  'CRM-974': 'Lo sentimos, no se encuentra disponible el servicio para cargar los tipos de comprobante de pago.',
  'CRM-975': 'Lo sentimos, no se encuentra disponible el servicio para realizar el pago.',
  'CRM-976': 'Lo sentimos, no se encuentra disponible el servicio para anular el pago.',
  'CRM-977': 'Se ha superado los reintentos permitidos de biometría, por favor genere nuevamente el pedido.',
  'CRM-978': 'Se ha superado los reintentos permitidos al grabar la venta, por favor genere nuevamente el pedido.',
  'CRM-979': 'Lo sentimos, no se encuentra disponible el servicio para obtener la información de pagos.',
  'CRM-980': 'No posee los permisos requeridos para realizar esta operación.',
  'CRM-981': 'Lo sentimos, no se encuentra disponible el servicio para validar la portabilidad.',

  'CRM-990': 'Lo sentimos, no se encuentra disponible el servicio para cargar los documentos a pagar.',
  'CRM-991': 'Lo sentimos, no se encuentra disponible el servicio para cargar los documentos pagados.',
  'CRM-992': 'Lo sentimos, no se encuentra disponible el servicio para anular el documento.',
  'CRM-993': 'Lo sentimos, no se puede pagar un documento sin validación biométrica.',
  'CRM-994': 'Clave bloqueada, comunícate con tu administrador para desbloquear.',
  'CRM-995': 'Lo sentimos, no se puede pagar debido a que no se encuentran los datos del cliente.',

  'CRM-996': 'Lo sentimos, no se encuentra disponible el servicio para cargar lo tipos de reposición.',
  'CRM-997': 'Lo sentimos, no se encuentra disponible el servicio para validar el número con el que se hará la reposición.',
  'CRM-998': 'Lo sentimos, no se encuentra disponible el servicio para cargar lo tipos de renovación.',
  'CRM-999': 'Lo sentimos, no se encuentra disponible el servicio para validar el número con el que se hará la renovación.',

  'CRM-2000': 'Lo sentimos, no se encuentra disponible el servicio para obtener los puntos de venta.',
  'CRM-2001': 'Lo sentimos, no se encuentra disponible el servicio para obtener los vendedores.',
  'CRM-2002': 'Lo sentimos, no se encuentra disponible el servicio para obtener las cuentas de red.',
  'CRM-2003': 'Lo sentimos, no se encuentra disponible el servicio para validar el numero.',
  'CRM-2004': 'Lo sentimos, no se encuentra disponible el servicio para cargar los estados.',
  'CRM-2005': 'Lo sentimos, no se encuentra disponible el servicio para registrar al vendedor.',
  'CRM-2006': 'Lo sentimos, no se encuentra disponible el servicio para actualizar al vendedor.',


  'CRM-1000': 'Lo sentimos, no se encuentra disponible el servicio para validar la identidad del supervisor.',
  'CRM-1001': 'Lo sentimos, no se encuentra disponible el servicio para cargar los motivos del cliente.',
  'CRM-1002': 'Lo sentimos, no se encuentra disponible el servicio para cargar los motivos tgfi.',
  'CRM-1003': 'Lo sentimos, no se encuentra disponible el servicio para cargar los prefijos de la dirección.',
  'CRM-1004': 'Lo sentimos, no se encuentra disponible el servicio para cargar las fechas sugeridas.',
  'CRM-1005': 'Lo sentimos, no se encuentra disponible el servicio para verififcar las fechas disponibles.',
  'CRM-1006': 'Lo sentimos, no se encuentra disponible el servicio para cargar los centros de atención.',
  'CRM-1007': 'Lo sentimos, no se encuentra disponible el servicio para cargar los tipos de pago.',
  'CRM-1008': 'Lo sentimos, no se encuentra disponible el servicio para cargar los medios de pago.',
  'CRM-1009': 'Lo sentimos, no se encuentra disponible el servicio para cargar los tipos de entrega del material.',
  'CRM-1010': 'Lo sentimos, no se encuentra disponible el servicio para validar el stock.',

  'CRM-000': 'Lo sentimos, no se encuentra disponible el servicio para obtener la descripcion de los materiales.',
  'CRM-001': 'Lo sentimos, no se encuentra disponible el servicio para obtener las Series.',
  'CRM-002': 'Lo sentimos, no se encuentra disponible el servicio para obtener los Claro Puntos.',
  'CRM-003': 'Lo sentimos, no se encuentra disponible el servicio para la omisión de pin.',

  'CRM-004': 'Lo sentimos, no se encuentra disponible el servicio para listar Vendedores.',
  'CRM-005': 'Lo sentimos, no se encuentra disponible el servicio para listar tipos de documentos.',
  'CRM-006': 'Lo sentimos, no se encuentra disponible el servicio para dar de baja al vendedor.',

  'CRM-007': 'Lo sentimos, no se encuentra disponible el servicio para traer las preguntas de la no biometría.',
  'CRM-008': 'Lo sentimos, no se encuentra disponible el servicio para validar las respuestas de la no biometría.',
  '19002' : 'Ocurrió una excepción durante el proceso',
  '19003' : 'El programa no se encuentra licenciado',
  '19006' : 'Falla en la captura de la huella',
  '19014' : 'Se cancelo la captura de la huella',
  '19015' : 'Lector desconectado o no se detecta',
  '19017' : 'Tiempo de espera agotado',
  '19034' : 'Huella de baja calidad',
  '19035' : 'Error al cargar las librerías',
  '19036' : 'Posible dedo falso detectado'
};
