import { IBlockData, ISerie } from '../interfaces';
import { ClaroPoints } from './claro-points.model';
import { Campaign, IParameter, Plan, Price } from './';
import { Department, PopulatedCenter, Ubigeo } from './ubigeo.model';

export class Line {
  order: number;
  service: IParameter;
  operator: IParameter;
  modalityFrom: IParameter;
  phone: string;
  sequentialCode: string;
  saleOptions: IParameter[];
  modalityTo: IParameter;
  productType: IParameter;
  option: IParameter;
  iccid: ISerie;
  imei: ISerie;
  campaign: Campaign;
  price: Price;
  totalPrice: string;
  plan: Plan;
  promotion: IParameter;
  department: Department;
  ubigeo: Ubigeo;
  populatedCenter: PopulatedCenter;
  expanded: boolean;
  pricedi: string;
  typeOperation: IParameter;
  flagCustomer: string;
  flagTechnology: string;
  typeHlr: string;
  currentSerie: string;
  contractCodePublic: string;
  blockData: IBlockData;
  blockFlag: string;
  unblockFlagManual: string;
  customerReason: IParameter;
  tgfiReason: IParameter;
  claroPoints: ClaroPoints;
  loyaltyDiscountAmount: number;
  check: boolean;

  constructor(line: Line) {
    this.order = line.order ? line.order : 1;
    this.service = line.service ? line.service : null;
    this.operator = line.operator ? line.operator : null;
    this.modalityFrom = line.modalityFrom ? line.modalityFrom : null;
    this.phone = line.phone ? line.phone : '';
    this.sequentialCode = line.sequentialCode ? line.sequentialCode : '';
    this.saleOptions = line.saleOptions ? line.saleOptions : [];
    this.modalityTo = line.modalityTo ? line.modalityTo : null;
    this.productType = line.productType ? line.productType : null;
    this.option = line.option ? line.option : null;
    this.iccid = line.iccid ? line.iccid : null;
    this.imei = line.imei ? line.imei : null;
    this.campaign = line.campaign ? line.campaign : null;
    this.price = line.price ? line.price : null;
    this.totalPrice = line.totalPrice ? line.totalPrice : '0.00';
    this.plan = line.plan ? line.plan : null;
    this.department = line.department ? line.department : null;
    this.ubigeo = line.ubigeo ? line.ubigeo : null;
    this.populatedCenter = line.populatedCenter ? line.populatedCenter : null;
    this.expanded = line.expanded ? line.expanded : true;
    this.typeOperation = line.typeOperation ? line.typeOperation : null;
    this.flagCustomer = line.flagCustomer ? line.flagCustomer : null;
    this.flagTechnology = line.flagTechnology ? line.flagTechnology : null;
    this.typeHlr = line.typeHlr ? line.typeHlr : null;
    this.customerReason = line.customerReason ? line.customerReason : null;
    this.tgfiReason = line.tgfiReason ? line.tgfiReason : null;
    this.claroPoints = line.claroPoints ? line.claroPoints : null;
    this.loyaltyDiscountAmount = line.loyaltyDiscountAmount ? line.loyaltyDiscountAmount : null;
    this.contractCodePublic = line.contractCodePublic ? line.contractCodePublic : '';
    this.blockData = line.blockData ? line.blockData : null;
    this.blockFlag = line.blockFlag ? line.blockFlag : null;
    this.unblockFlagManual = line.unblockFlagManual ? line.unblockFlagManual : null;
    this.currentSerie = line.currentSerie ? line.currentSerie : '';
    this.check = line.check ? line.check : true;
  }
}
