export class Sale {
  orgSale: string;
  officetype: string;
  userAccount: string;
  salesCodeSap: string;
  codeOfficeSale: string;
  interlocutorCode: string;
  sisActUserCode: string;
  channel: string;
  channelDescription: string;
  officeDescription: string;
  nroSec: string;
  idBioParent: string;
  codDepartmentOffice: string;
  saleType: string;
  chainDeals: boolean[];
  customerParameters: CustomerParameters;
  listSeries: ListSerie[];
  customerCode: string;
  productType: string;
  documentVendor: string;
  nameVendor: string;
  typeOperation: string;
  descOperation: string;
  codeReplacement: string;
  descReplacement: string;
  flagMultipoint: string;
  multipointSeller: string;
  loginOfficeCode: string;
  dispatchType: string;
  customerCodePublic: string;
  contractCodePublic: string;
  flagPicking: string;
  flagDelivery: string;
  reasonRepoCode: string;
  reasonRepoDesc: string;
  tgfi: boolean;
  tgfiDescription: string;
  claroclubCampaignCode: string;
  claroclubcampaignDescription: string;
  discountLoyalty: string;
  factorConvert: string;
  codeCampana: string;
  descCampana: string;
  totalPoints: string;
  discountAmount: string;
  usePoints: string;
  imeiPicking: string;
  deliveryParameters: DeliveryParameters;

  constructor() {
    this.orgSale = '';
    this.officetype = '';
    this.userAccount = '';
    this.salesCodeSap = '';
    this.codeOfficeSale = '';
    this.interlocutorCode = '';
    this.sisActUserCode = '';
    this.channel = '';
    this.channelDescription = '';
    this.officeDescription = '';
    this.nroSec = '';
    this.idBioParent = '';
    this.codDepartmentOffice = '';
    this.saleType = '';
    this.chainDeals = [];
    this.customerParameters = new CustomerParameters();
    this.listSeries = [];
    this.customerCode = '';
    this.productType = '';
    this.documentVendor = '';
    this.nameVendor = '';
    this.typeOperation = '';
    this.descOperation = '';
    this.codeReplacement = '';
    this.descReplacement = '';
    this.customerCodePublic = '';
    this.contractCodePublic = '';
    this.flagMultipoint = '';
    this.flagPicking = '';
    this.flagDelivery = '';
    this.reasonRepoCode = '';
    this.reasonRepoDesc = '';
    this.tgfi = false;
    this.tgfiDescription = '';
    this.claroclubCampaignCode = '';
    this.claroclubcampaignDescription = '';
    this.multipointSeller = '';
    this.loginOfficeCode = '';
    this.dispatchType = '';
    this.discountLoyalty = '';
    this.factorConvert = '';
    this.codeCampana = '';
    this.descCampana = '';
    this.totalPoints = '';
    this.discountAmount = '';
    this.usePoints = '';
    this.imeiPicking = '';
    this.deliveryParameters = new DeliveryParameters();
  }
}

export class CustomerParameters {
  phoneNumber: string;
  email: string;
  billingEmail: string;
  documentTypePVU: string;
  documentNumber: string;
  name: string;
  firstName: string;
  secondName: string;
  birthDate: string;
  expirationDate: string;
  gender: string;
  businessName: string;
  origin: string;
  direction: string;
  codDepartment: string;
  codProvince: string;
  codDistrict: string;
  phoneReference: string;
  ubigeo: string;
  civilState: string;
  nationality: string;
  nationalityDescription: string;
  descDepartment: string;
  descProvince: string;
  descDistrict: string;
  imei: string;

  constructor() {
    this.phoneNumber = '';
    this.email = '';
    this.billingEmail = '';
    this.documentTypePVU = '';
    this.documentNumber = '';
    this.name = '';
    this.firstName = '';
    this.secondName = '';
    this.birthDate = '';
    this.expirationDate = '';
    this.gender = '';
    this.businessName = '';
    this.origin = '';
    this.direction = '';
    this.codDepartment = '';
    this.codProvince = '';
    this.codDistrict = '';
    this.phoneReference = '';
    this.ubigeo = '';
    this.civilState = '';
    this.nationality = '';
    this.nationalityDescription = '';
    this.descDepartment = '';
    this.descProvince = '';
    this.descDistrict = '';
    this.imei = '';
  }
}

export class DeliveryParameters {
  name: string;
  phone: string;
  email: string;
  addressPrefixCode: string;
  addressPrefixDescription: string;
  addressName: string;
  addressNumber: string;
  addressTypeCode: string;
  addressTypeDescription: string;
  blockNumber: string;
  lotNumber: string;
  department: string;
  province: string;
  district: string;
  address: string;
  reference: string;
  deliveryDate: string;
  deliveryTimeRange: string;
  paymentTypeCode: string;
  paymentModeCode: string;
  paymentModeDescription: string;
  paymentId: string;
  placementCall: string;
  placementInOut: string;
  details: string;

  constructor() {
    this.name = '';
    this.phone = '';
    this.email = '';
    this.addressPrefixCode = '';
    this.addressPrefixDescription = '';
    this.addressName = '';
    this.addressNumber = '';
    this.addressTypeCode  = '';
    this.addressTypeDescription = '';
    this.blockNumber = '';
    this.lotNumber = '';
    this.department = '';
    this.province = '';
    this.district = '';
    this.address = '';
    this.reference = '';
    this.deliveryDate = '';
    this.deliveryTimeRange = '';
    this.paymentTypeCode = '';
    this.paymentModeCode = '';
    this.paymentModeDescription = '';
    this.paymentId = '';
    this.placementCall = '';
    this.placementInOut = '';
    this.details = '';
  }
}

export class ListSerie {
  serie: string;
  sequenceNumber: string;
  codisPack: string;
  codFamily: string;
  code: string;
  description: string;
  phoneNumber: string;
  codAssignorOperator: string;
  salePrice: string;
  codListPrice: string;
  descListPrice: string;
  codCampana: string;
  desCampana: string;
  codPromotion: string;
  descPromotion: string;
  descCode: string;
  descPlan: string;
  productOfferId: string;
  basePrice: string;
  totalPrice: string;
  igvValue: string;
  discount: string;
  type: string;
  flagLP: string;
  productType: string;
  operationPre: string;
  coberCodDepartment: string;
  coberDescDepartment: string;
  coberCodProvince: string;
  coberDesProvince: string;
  coberCodDistrict: string;
  coberDescDistrict: string;
  coberCodUbigeoINEI: string;
  coberDesUbigeoINE: string;
  ordnIdMaterial: string;
  sku: string;
  skuAlt: string;
  priceAlt: string;
  materialAltern: string;
  codeListPriceAlt: string;
  currentSerie: string;
  conversionFactor: string;
  discountPoints: string;
  discountLoyalty: string;
  usedPoints: string;
  grossPrice: string;
  oldTechnology: string;
  newTechnology: string;
  blockFlag: string;
  blockType: string;
  blockStatus: string;
  blockCode: string;
  pointsPostpago: string;
  pointsPrepago: string;
  pointsHFC: string;
  pointsDTH: string;

  constructor() {
    this.serie = '';
    this.sequenceNumber = '';
    this.codisPack = '';
    this.codFamily = '';
    this.code = '';
    this.description = '';
    this.phoneNumber = '';
    this.codAssignorOperator = '';
    this.salePrice = '';
    this.codListPrice = '';
    this.descListPrice = '';
    this.codCampana = '';
    this.desCampana = '';
    this.codPromotion = '';
    this.descPromotion = '';
    this.descCode = '';
    this.descPlan = '';
    this.productOfferId = '';
    this.basePrice = '';
    this.totalPrice = '';
    this.igvValue = '';
    this.discount = '';
    this.type = '';
    this.flagLP = '';
    this.productType = '';
    this.operationPre = '';
    this.coberCodDepartment = '';
    this.coberDescDepartment = '';
    this.coberCodProvince = '';
    this.coberDesProvince = '';
    this.coberCodDistrict = '';
    this.coberDescDistrict = '';
    this.coberCodUbigeoINEI = '';
    this.coberDesUbigeoINE = '';
    this.ordnIdMaterial = '';
    this.sku = '';
    this.skuAlt = '';
    this.priceAlt = '';
    this.materialAltern = '';
    this.codeListPriceAlt = '';
    this.currentSerie = '';
    this.conversionFactor = '';
    this.discountPoints = '';
    this.discountLoyalty = '';
    this.usedPoints = '';
    this.grossPrice = '';
    this.oldTechnology = '';
    this.newTechnology = '';
    this.blockFlag = '';
    this.blockType = '';
    this.blockStatus = '';
    this.blockCode = '';
    this.pointsPostpago = '';
    this.pointsPrepago = '';
    this.pointsHFC = '';
    this.pointsDTH = '';
  }
}
